# Dependencies
markdown            : kramdown
extensions          : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink           : pretty
# relative_permalinks: true

# Setup
title               : Alex's Blog
tagline             : 'JavaScript, Python and Web development frameworks'
description         : 'Articles of web development'
url                 : http://gtopia.github.io/
baseurl             : ''
paginate            : 5

# About/contact
author              : Alex Gao
name                : 'Alex Gao'

# Custom vars
version             : 0.1.0
github_username     : gtopia

